?mtcars
df <- mtcars
str(df)
df$vs <- factor(df$vs, labels = c("V","S"))
df$am <- factor(df$am, labels = c("Auto", "Manual"))
median(df$mpg)
mean(df$disp)
sd(df$hp)
range(df$cyl)
mean(df$mpg[df$cyl == 6])
mean(df$mpg[df$cyl == 6 & df$vs == "V"])
result <- mean(df$qsec[df$cyl!=3 & df$mpg >20])
mean_hp_vs = aggregate(x= df$hp, by = list(df$vs), FUN = mean)
colnames(mean_hp_vs) <- c("VS","Mean HP")
aggregate(hp ~ vs, df, mean)
aggregate(hp ~ vs + am, df, mean)
aggregate(x= df[,-c(8,9)], by = list(df$am), FUN = median)
aggregate(x= df[,c(1,3)], by = list(df$am, df$vs), FUN = sd)
aggregate(cbind(mpg,disp) ~ am+vs,df,sd)
descriptions_stat <- aggregate(cbind(hp,disp) ~ am, df, sd)
library(psych)
describe(x = df)
desc2 <- describeBy(x = df[,-c(8,9)], group = df$vs, mat = T, digits = 2)
desc3 <- describeBy(x = df[,-c(8,9)], group = df$vs, mat = T, digits = 2, fast = T)
desc4 <- describeBy(df$qsec, group = list(df$vs,df$am), mat = T, digits = 1,fast = T)
